diseases = {
    'covid19': {
        'name': 'COVID-19',
        'keywords': ['covid', 'covid-19', 'coronavirus', 'sars-cov-2'],
        'symptoms': 'Fever, cough, shortness of breath, loss of taste/smell, fatigue, body aches',
        'prevention': 'Wear masks, social distancing, vaccination, hand hygiene, avoid crowds',
        'treatment': 'Rest, hydration, seek medical help if severe symptoms appear',
        'awareness': 'COVID-19 is caused by SARS-CoV-2. Stay updated with local health guidelines.',
    },
    'diabetes': {
        'name': 'Diabetes',
        'keywords': ['diabetes', 'diabetic', 'blood sugar', 'insulin'],
        'symptoms': 'Frequent urination, excessive thirst, fatigue, blurred vision, slow-healing sores',
        'prevention': 'Healthy diet, regular exercise, maintain healthy weight, regular check-ups',
        'treatment': 'Medication, insulin, lifestyle changes, blood sugar monitoring',
        'awareness': 'Diabetes affects blood sugar levels. Regular check-ups are important.',
    },
    'hypertension': {
        'name': 'Hypertension (High Blood Pressure)',
        'keywords': ['hypertension', 'high blood pressure', 'bp', 'blood pressure'],
        'symptoms': 'Often asymptomatic, headaches, dizziness, chest pain, shortness of breath',
        'prevention': 'Low salt diet, exercise, stress management, medication if prescribed',
        'treatment': 'Lifestyle changes, antihypertensive drugs, regular monitoring',
        'awareness': 'Monitor blood pressure regularly. Untreated hypertension can lead to heart disease.',
    },
    'malaria': {
        'name': 'Malaria',
        'keywords': ['malaria', 'malarial'],
        'symptoms': 'Fever, chills, headache, nausea, vomiting, muscle pain',
        'prevention': 'Use mosquito nets, insect repellents, antimalarial drugs in endemic areas',
        'treatment': 'Antimalarial medications like chloroquine or artemisinin-based drugs',
        'awareness': 'Malaria is transmitted by mosquitoes. Seek treatment promptly.',
    },
    'tuberculosis': {
        'name': 'Tuberculosis (TB)',
        'keywords': ['tuberculosis', 'tb', 'tubercles'],
        'symptoms': 'Persistent cough, weight loss, fever, night sweats, chest pain',
        'prevention': 'Vaccination (BCG), good ventilation, treatment of latent TB',
        'treatment': 'Antibiotic regimen for 6-9 months (usually rifampin and isoniazid)',
        'awareness': 'TB is curable with proper treatment. Complete the full course of medication.',
    },
    'dengue': {
        'name': 'Dengue Fever',
        'keywords': ['dengue', 'dengue fever', 'breakbone fever'],
        'symptoms': 'High fever, severe headache, pain behind eyes, joint/muscle pain, rash',
        'prevention': 'Use mosquito repellents, wear protective clothing, eliminate breeding sites',
        'treatment': 'Rest, fluids, pain relievers, seek medical attention for severe cases',
        'awareness': 'Dengue is transmitted by Aedes mosquitoes. Severe dengue can be life-threatening.',
    },
    'asthma': {
        'name': 'Asthma',
        'keywords': ['asthma', 'asthmatic'],
        'symptoms': 'Shortness of breath, wheezing, chest tightness, coughing',
        'prevention': 'Avoid triggers, use inhalers as prescribed, regular check-ups',
        'treatment': 'Bronchodilators, corticosteroids, lifestyle modifications',
        'awareness': 'Asthma is a chronic respiratory condition. Proper management prevents attacks.',
    },
    'cancer': {
        'name': 'Cancer',
        'keywords': ['cancer', 'tumor', 'malignant', 'carcinoma'],
        'symptoms': 'Varies by type - unexplained weight loss, fatigue, pain, lumps',
        'prevention': 'Healthy lifestyle, regular screenings, avoid risk factors',
        'treatment': 'Surgery, chemotherapy, radiation, immunotherapy',
        'awareness': 'Early detection improves treatment success. Regular health check-ups are crucial.',
    },
    'flu': {
        'name': 'Influenza (Flu)',
        'keywords': ['flu', 'influenza', 'seasonal flu'],
        'symptoms': 'Fever, chills, body aches, fatigue, cough, sore throat',
        'prevention': 'Annual vaccination, hand hygiene, avoid close contact with sick people',
        'treatment': 'Rest, fluids, antiviral medications, pain relievers',
        'awareness': 'Flu can be serious, especially for vulnerable groups. Get vaccinated annually.',
    },
    'hiv': {
        'name': 'HIV/AIDS',
        'keywords': ['hiv', 'aids', 'human immunodeficiency virus'],
        'symptoms': 'Early: fever, fatigue, swollen lymph nodes. Later: opportunistic infections',
        'prevention': 'Safe sex practices, condom use, HIV testing, PrEP for high-risk groups',
        'treatment': 'Antiretroviral therapy (ART), regular medical care',
        'awareness': 'HIV is manageable with treatment. Early diagnosis and treatment are key.',
    },
}